version: "3.8"

services:
  frontend:
    platform: linux/amd64
    image: ghcr.io/cmi-dair/ctk-frontend:main
    ports:
      - 3000:3000
    environment:
      - VITE_API_URL=http://api:8000
    networks:
      - frontend_api

  api:
    platform: linux/amd64
    image: ghcr.io/cmi-dair/ctk-api:main
    ports:
      - 8000:8000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELASTIC_URL=http://elasticsearch:9200
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - frontend_api
      - api_postgresql

  postgresql:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - api_postgresql


networks:
  frontend_api:
  api_postgresql:
