services:
  frontend:
    image: ghcr.io/cmi-dair/ctk-frontend:main
    ports:
      - 3000:3000
    environment:
      - VITE_API_URL=http://api:8000

  api:
    image: ghcr.io/cmi-dair/ctk-api:main
    ports:
      - 8000:8000
    env_file:
      - .env
